### ISSUE TITLE
Breaks running under thin-2.0.0pre

### ISSUE THREAD

**Issue by binford2k** [gruis/sinatra-websocket#12]
Stack trace

```
/usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-websocket-0.3.0/lib/sinatra-websocket/ext/thin/connection.rb:16:in `block in included': undefined method `pre_process' for class `Thin::Connection' (NameError)
    from /usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-websocket-0.3.0/lib/sinatra-websocket/ext/thin/connection.rb:6:in `class_eval'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-websocket-0.3.0/lib/sinatra-websocket/ext/thin/connection.rb:6:in `included'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-websocket-0.3.0/lib/sinatra-websocket/ext/thin/connection.rb:76:in `include'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-websocket-0.3.0/lib/sinatra-websocket/ext/thin/connection.rb:76:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/sinatra-websocket-0.3.0/lib/sinatra-websocket.rb:4:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/showoff-0.9.7.1/lib/showoff.rb:8:in `<top (required)>'
    from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/rvm/gems/ruby-2.1.1/gems/showoff-0.9.7.1/bin/showoff:4:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/showoff:23:in `load'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/showoff:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

From https://github.com/puppetlabs/showoff/issues/122

**Comment by dux** [comment]
same here
