### ISSUE TITLE
Error while running with Rainbows!

### ISSUE THREAD

**Issue by d4l3k** [gruis/sinatra-websocket#5]
When I try to use the server Rainbows! with sinatra-websocket I get this error.

```
NoMethodError - undefined method `backend' for #<Rainbows::EventMachine::Client:0x9c3fa60>:
    /home/foo/.rvm/gems/ruby-1.9.3-p392/gems/sinatra-websocket-0.2.1/lib/sinatra-websocket.rb:92:in `initialize'
    /home/foo/.rvm/gems/ruby-1.9.3-p392/gems/sinatra-websocket-0.2.1/lib/sinatra-websocket.rb:60:in `new'
    /home/foo/.rvm/gems/ruby-1.9.3-p392/gems/sinatra-websocket-0.2.1/lib/sinatra-websocket.rb:12:in `from_env'
    /home/foo/.rvm/gems/ruby-1.9.3-p392/gems/sinatra-websocket-0.2.1/lib/sinatra-websocket/ext/sinatra/request.rb:17:in `websocket'
    /home/foo/Git/bar/main.rb:104:in `block in <top (required)>'
```

My rainbows.conf:

```
Rainbows! do
    use :EventMachine
    worker_connections 400
end

worker_processes 4
```

**Comment by dulumao** [comment]
the same as @d4l3k
